table _Misure_Ferdinando
	lineageTag: 0f02df18-4e32-4ecf-a412-e61244a81f6c

	measure 'AVG RATING' = ```
			AVERAGE(DIM_reviews[rating]) 
			```
		lineageTag: e7e82376-4a18-4219-9fe8-6b6fe027494a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Trips' = COUNTROWS(fact_trips)
		formatString: 0
		lineageTag: 843eecd7-536a-4cc0-9466-776f8d935d1e

	measure 'Total Revenue' = SUM(fact_trips[total_fare])
		lineageTag: 3171368c-283e-41d8-bdd2-779297c29bc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Misure_Ferdinando = m
		mode: import
		source =
				let
				    Origine = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Colonna1 = _t]),
				    #"Modificato tipo" = Table.TransformColumnTypes(Origine,{{"Colonna1", type text}}),
				    #"Rimosse colonne" = Table.RemoveColumns(#"Modificato tipo",{"Colonna1"})
				in
				    #"Rimosse colonne"

	annotation PBI_ResultType = Table

