table misure
	lineageTag: 5458ae99-4529-4762-a19b-9c7b7300a5d4

	measure 'Total Trips' =
			
			COUNT(fact_trips[trip_id])
		formatString: 0
		lineageTag: d9659c59-8d4c-43af-97e8-38c807e645e7

	measure 'Total Revenue' =
			
			SUM(fact_trips[total_fare])
		lineageTag: e3369eee-942a-44e9-9c29-3e9caa141452

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Driver Rating' =
			
			AVERAGE(dim_drivers[driver_rating])
		lineageTag: ba26a625-8722-413e-81f5-a4badbba88cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: d18a6e25-60a6-4946-8ba3-0d714f8d5e63
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition misure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 0187f6df48fc4b73b8b5c3e8d39d1615

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

