table Misure_Saverio
	lineageTag: d63d9e41-d538-4807-ac81-42d90f360ee0

	measure GaugMaxRating = 5
		formatString: 0
		lineageTag: 12a15ae5-a573-4451-8cec-22f580426031

	measure GaugMinRating = 1
		formatString: 0
		lineageTag: bc60d65d-afbe-4538-a679-8c8bf8a7f483

	measure TargetRating = 3.65
		formatString: 0
		lineageTag: 44b9e727-2658-4321-a35c-224cda0bb60d

	measure MinPearson = -1
		formatString: 0
		lineageTag: 2b8e09cb-f470-447c-a110-ec2a91f4735a

	measure MaxPearson = 1
		formatString: 0
		lineageTag: 59b7a6ac-799a-437c-855b-dc2a3b0d1a33

	measure TargetPearson = 0
		formatString: 0
		lineageTag: 93bc9610-cfc1-400c-a1fb-8cd229fed072

	measure IndicePearson1 = ```
			
			VAR TabellaDati = 
			    SELECTCOLUMNS(
			        'dim_drivers',
			        "X", 'dim_drivers'[years_experience],
			        "Y", 'dim_drivers'[driver_rating]
			    )
			VAR TabellaPulita = 
			    FILTER(
			        TabellaDati, 
			        NOT(ISBLANK([X])) && NOT(ISBLANK([Y]))
			    )
			VAR MediaX = AVERAGEX(TabellaPulita, [X])
			VAR MediaY = AVERAGEX(TabellaPulita, [Y])
			
			VAR Numeratore = 
			    SUMX(TabellaPulita, ([X] - MediaX) * ([Y] - MediaY))
			
			VAR Denominatore = 
			    SQRT(
			        SUMX(TabellaPulita, POWER([X] - MediaX, 2)) * SUMX(TabellaPulita, POWER([Y] - MediaY, 2))
			    )
			
			RETURN 
			    DIVIDE(Numeratore, Denominatore)
			```
		lineageTag: 5c96af2c-093d-4ff6-a89e-9cfa25d0d70a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Correlazione1 = [IndicePearson1]*2
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 75a81111-3869-48a8-8cae-3b6f86e8ee64

	measure IndicePearson2 = ```
			
			VAR TabellaDati = 
			    SELECTCOLUMNS(
			        'fact_trips',
			        "X", RELATED('dim_drivers'[years_experience]),
			        "Y", 'fact_trips'[payment_amount]
			    )
			VAR TabellaPulita = 
			    FILTER(
			        TabellaDati, 
			        NOT(ISBLANK([X])) && NOT(ISBLANK([Y]))
			    )
			VAR MediaX = AVERAGEX(TabellaPulita, [X])
			VAR MediaY = AVERAGEX(TabellaPulita, [Y])
			
			VAR Numeratore = 
			    SUMX(TabellaPulita, ([X] - MediaX) * ([Y] - MediaY))
			
			VAR Denominatore = 
			    SQRT(
			        SUMX(TabellaPulita, POWER([X] - MediaX, 2)) * SUMX(TabellaPulita, POWER([Y] - MediaY, 2))
			    )
			
			RETURN 
			    DIVIDE(Numeratore, Denominatore)
			```
		lineageTag: b6d7cd31-2dc6-47ce-b907-9d41c0844083

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Correlazione2 = [IndicePearson2]*2
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 624fcf92-fb42-4644-8056-290f20b9c359

	partition Misure_Saverio = m
		mode: import
		source =
				let
				    Origine = {...},
				    #"Rimosse colonne" = Table.RemoveColumns(Origine,{"Misure_Saverio"})
				in
				    #"Rimosse colonne"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = List

